return PlaceObj('ModDef', {
	'title', "Rato's ToG Compatibility Patch & Rebalance",
	'description', "[h1](Partial) Compatibility patch for Rato's Gameplay Balance and Overhaul and Tons of Guns[/h1]\n\n	\nWill balance and patch a number of guns of ToG to work with Rato's Mod. \n\n\nIt is recommended to start a fresh game. Will cause compatibility issues on a already ToG enabled save.\n\nPatched Weapons:\n\nRifles:\n[list]\n[*]AN 94\n[*]SKS\n[*]Papovka\n[*]Type 56\n[*]STG44\n[*]Gewehr 43\n[*]Groza\n[*]M1 Garand\n[*]HK33A2\n[*]G3A3\n[*]M70\n[*]TAR 21\n[*]RK 95\n[*]RK 62\n\n[/list]\nPrecision Rifles:\n[list]\n[*]Mosin Carbine\n[*]VSS Vintorez\n[*]SSG 69\n[*]Steyr Scout Elite\n[*]M76\n[*]Delisle\n[*]VSK94\n[/list]\n\nSMGs:\n[list]\n[*]P90\n[*]Micro Uzi\n[*]Sten MK2\n[*]Mac11\n[*]HK53\n[*]UMP\n[*]PP91\n[*]Vigneron M2\n[/list]\n\nPistols:\n[list]\n[*]Glock17\n[*]USP\n[*]Viking Mp446\n[*]B93R\n[*]P 08 Luger\n[*]M1911\n[/list]\n\nMachine Guns:\n[list]\n[*]RPD\n[*]PKM\n[*]HK23E\n[/list]\n\n\n\nSome other changes:\nChanges some components installation logic.\nPapovka Grenade Launcher now blocks the gun from shooting, and appends a grenade to the muzzle\n\n\n[b]Also includes new calibers from Zulib[/b]\n\n[b]Works with Random Enemy Weapons[/b]: I recommend using the 75% chance of Default Weapon for now.\n\nUnpatched weapons won't drop and won't appear on Bobby Rays\n\nImportant: If you use DiceMan Adaptative Difficulty, you will need to turn OFF the dynamic equipment option. Or unpatched guns will drop.\n\n[b]Big thanks to Archimedes, the creator of ToG, and to Wittzard for helping the mod community with a lot of coding stuff[/b]",
	'image', "Mod/Dau6w/Images/tog.PNG",
	'last_changes', "1.19c\n\nremoved unused calibers from appearing in Bobby Rays",
	'dependencies', {
		PlaceObj('ModDependency', {
			'id', "cfahRED",
			'title', "[JA 1.3] Rato's Gameplay Balance and Overhaul 3",
			'version_major', 3,
			'version_minor', 50,
		}),
		PlaceObj('ModDependency', {
			'id', "KKh3Yhf",
			'title', "Tons of Guns",
			'version_major', 1,
			'version_minor', 20,
		}),
	},
	'id', "Dau6w",
	'author', "rato",
	'version_major', 1,
	'version_minor', 19,
	'version', 2920,
	'lua_revision', 233360,
	'saved_with_revision', 350233,
	'code', {
		"Code/FUNCTION_CombatActions.lua",
		"Code/Dependancy_fix.lua",
		"Code/OnDataLoaded_call.lua",
		"Code/REW_table.lua",
		"Code/FUNCTION_bipod_change.lua",
		"Code/PATCH_Guns.lua",
		"Code/WEAPON_COMPONENTS_components.lua",
		"Code/FUNCTION_grenade_launcher_22.lua",
		"Code/explosion_inherit.lua",
		"InventoryItem/_22m_HE.lua",
		"InventoryItem/rat_22mmUnderslungGrenadeLauncher.lua",
	},
	'default_options', {},
	'has_data', true,
	'saved', 1724219740,
	'code_hash', -7750895765134797104,
	'affected_resources', {
		PlaceObj('ModResourcePreset', {
			'Class', "Caliber",
			'Id', "22m_grenade",
			'ClassDisplayName', "Caliber mod",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "Rat_p08_bunker_ernie_1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "LootDef",
			'Id', "RatBunker_GewerS_1",
			'ClassDisplayName', "Loot definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXObject",
			'Id', "B531tcc7",
			'ClassDisplayName', "ActionFX Object",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "ActionFXObject",
			'Id', "Lb9Q46f_",
			'ClassDisplayName', "ActionFX Object",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "_22m_HE",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CraftOperationsRecipeDef",
			'Id', "_22mmhe_craft",
			'ClassDisplayName', "Crafting operation recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "rat_22mmUnderslungGrenadeLauncher",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "foldable_StockNormal",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "R_TOG_light_barrel",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "R_VSS_suppressor",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_VSK_Suppressor",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_pap_compensator",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "_Rat_Bay_unfolded_master",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "StockFolded_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "component_22mm_grenade",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_suppressor",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_suppressor_wp",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_suppressor_762",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_compensator",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_ACOG",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_ACOG_rpk_mount",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_WideScope",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_WideScope_rpk_mount",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_LRoptics",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_LRoptics_rpk_mount",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_PSGScope",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_PSGScope_rpk_mount",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_Reflex",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_Reflex_rpk_mount",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_Reflex_pistol",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_Reflex_pistol_rpk_mount",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_LRoptics_advanced",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_LRoptics_advanced_rpk_mount",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_thermal",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_thermal_rpk_mount",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ThermalScope_2",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ThermalScope_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_compactRS",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_compactRS_rpk_mount",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_vigilanceRS",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_vigilanceRS_rpk_mount",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_Prism",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_Prism_rpk_mount",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_flashlight",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_flashlight_rpk_mount",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_tactical_dot",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_tactical_dot_rpk_mount",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_laser_dot",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_laser_dot_rpk_mount",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_uv_dot",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_uv_dot_rpk_mount",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_SteyrS_Barrel_ext_556",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_TOG_SteyrS_Barrel_def_555",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "B93RR_mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "B93RR_mag_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "B93RR_barrel_shrt_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "B93RR_barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "B93RR_barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "B93RR_grip_fld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "B93RR_grip_unfld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "DeLisle_barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "DeLisle_mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "DeLisle_stock_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "DeLisle_stock_erg_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G3A3_barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G3A3_barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G3A3_barrel_shrt_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G3A3_magazine_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G3A3_Stock_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G3A3_muzzle_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G3A3_stock_hvy_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G3_Stock_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G3_Muzzle_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G3_Mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G3_Mag_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G3_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G3_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M70_stock_fld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M70_stock_unfld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M70_mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M70_grndl_fld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M70_grndl_unfld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M70_barrel_shrt_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M70_barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M70_barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M70D_stock_fld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M70D_stock_unfld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M70D_mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M70D_grndl_fld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M70D_grndl_unfld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M70D_barrel_shrt_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M70D_barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M70D_barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "VigM2_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "VigM2_Barrel_shrt_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "VigM2_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "VigM2_mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "VigM2_Stock_fld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "VigM2_Stock_unfld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "VigM2_Stock_hlffld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "m76_barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "m76_barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "m76_barrel_shrt_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "m76_mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "m76_scope_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "m76_stock_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "m76_stock_erg_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "m76_stock_hvy_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "hk33_barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "hk33_barrel_shrt_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "hk33_barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "hk33_magazine_31",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "hk33_magazine_11",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "hk33_drum_mag_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "hk33_Stock_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "hk53_Stock_heavy",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "hk33_bipod_fld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "hk33_bipod_unfld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "hk33_handguard_cl_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "hk33_handguard_new_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "hk33_lower_classic_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "hk33_lower_modern_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "hk33_muzzle_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "hk33_side_rails_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "hk33_side_block_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "hk33_top_rail_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "HK53_stock_fld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "HK53_stock_unfld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "hk23e_barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "hk23e_barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "hk23e_barrel_shrt_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "hk23e_stock_hvy_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "hk23e_stock_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "hk23e_mag_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "hk23e_bipod_fld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "hk23e_bipod_unfld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "hk23e_handle_fld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "hk23e_handle_unfld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "hk23e_muzzle_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "hk23e_sidegrip_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "hk23e_siderail_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "hk23e_rail_top_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "hk23e_stock_erg_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M1918A2_mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M1918A2_mag_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M1918A2_handle_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M1918A2_muzzle_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RPD_barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RPD_mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RPD_ironsight_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RPD_bipod_fld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RPD_bipod_unfld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RPD_stock_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "VSK94_Mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "VSK94_Pistolgrip_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "VSK94_stock_fld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "VSK94_stock_unfld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "VSK94_Stock_hvy_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "VSK94_barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "PP91_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "PP91_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "PP91_Mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "PP91_Mag_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "PP91_Stock_fld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "PP91_Stock_unfld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Viking_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Viking_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Viking_mag_extQ_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Viking_mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Viking_mag_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Papovka_Stock_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Papovka2_Stock_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Papovka_Stock_def_cross1_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Papovka2_Stock_def_cross1_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Papovka_Stock_erg_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Papovka2_Stock_erg_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Papovka_Stock_erg_cross1_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Papovka2_Stock_erg_cross1_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Papovka_Stock_hvy_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Papovka2_Stock_hvy_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Papovka_Stock_hvy_cross1_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Papovka2_Stock_hvy_cross1_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Papovka_Stock_def_type56_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Papovka_Bolt_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Papovka2_Bolt_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Papovka_Barrel_shrt_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RAT_short_barrel_master",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Papovka2_Barrel_shrt_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Papovka_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Papovka2_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Papovka_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Papovka2_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Papovka_Mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Papovka2_Mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Papovka_Mag_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Papovka2_Mag_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Papovka_Mag_ext_c_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Papovka2_Mag_ext_c_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Papovka_Bay_fld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "_Rat_bay_folded_master",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Papovka2_Bay_fld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Papovka_Grnd_unfld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "_Rat_grn_unfolded_master",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Papovka2_Grnd_unfld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Papovka_Grnd_fld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "_Rat_Grn_Folded_master",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Papovka2_Grnd_fld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MP7_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MP7_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MP7_Mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MP7_Mag_quick_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MP7_Mag_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MP7_Mag_extQ_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MP7_Ironsight_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MP7_Scope_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MP7_Grip_fld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MP7_Grip_unfld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MP7_Supr_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MP7_stock_fld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MP7_stock_unfld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MP7_siderails_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RK95_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RK95_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RK95_Barrel_shrt_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RK95_Mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RK95_Mag_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RK95_Stock_shrt_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RK95_Stock_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RK95_Irons_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RK95_Muzzle_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RK95_Handguard_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RK95_Handguard_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RK95_Handguard_shrt_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RK62_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RK62_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RK62_Barrel_shrt_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RK62_Mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RK62_Mag_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RK62_Mag_def_3",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RK62_Stock_hvy_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RK62_Stock_shrt_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RK62_Stock_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RK62_Irons_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RK62_Muzzle_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RK62_Handguard_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RK62_Handguard_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "RK62_Handguard_shrt_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MicroUZI_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MicroUZI_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MicroUZI_Mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MicroUZI_Mag_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MicroUZI_Scope_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Condor_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Condor_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Condor_Barrel_shrt_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "CondorN_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "CondorN_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "CondorN_Barrel_shrt_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Condor_Mag_fed_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Condor_Mag_magn_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Condor_Mag_XX_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Condor_Holder_black_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Condor_Holder_magblock_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Condor_Holder_tan_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Condor_Holder_green_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Condor_Stock_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "CondorN_Stock_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M1911_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M1911_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M1911_Mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M1911_Mag_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Mac11_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Mac11_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Mac11_Mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Mac11_Stock_fld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Mac11_Stock_unfld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "SteyrS_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "SteyrS_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "SteyrS_Scope_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "SteyrS_Muzzle_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Stechkin_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Stechkin_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BrenMK1_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BrenMK1_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BrenMK1_Barrel_shrt_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BrenMK1_Mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BrenMK1_Mag_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BrenMK1_Stock_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BrenMK1_Stock_shrt_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BrenMK1_Stock_hvy_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BrenMK1_Bipod_fld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "BrenMK1_Bipod_unfld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Tokarev_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Tokarev_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Tokarev_Mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Tokarev_Mag_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "LeeEn_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "LeeEn_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "LeeEn_Stock_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "LeeEn_Stock_erg_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "LeeEn_Stock_Heavy_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "LeeEn_Irons_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "LeeEn_Mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "uspr_mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "uspr_mag_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "AWP_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "AWP_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "AWP_mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "AWP_mag_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "AWP_Scope_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "AWP_Muzzle_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "AWP_Stock_rst_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "AWP_rail_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "AN94_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "AN94_Barrel_short_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "AN94_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "AN94_Mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "AN94_Mag_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "AN94_Stock_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "AN94_Stock_fld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "AN94_Bip_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "AN94_Scope_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Automag_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Automag_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Automag_Mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Automag_Mag_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Automag_Scope_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Automag_Stock_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M60_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M60_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M60_Mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M60_Mag_bag_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M60_Muzzle_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M60_Irons_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M60_Stock_hvy_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M60_Stock_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M60_Stock_erg_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M60_Bip_fld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M60_Bip_unfld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M60_Grip_und_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M60_Grip_side_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M60_GrenadeLauncher_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "PPSh_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "PPSh_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "PPSh_Mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "PPSh_Mag_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "PPSh_Scope_iron_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "PPSh_Stock_heavy_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "PPSh_Stock_short_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "PPSh_Stock_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Caws_Ironsight_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Caws_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Caws_Barrel_long_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Caws_Grip_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Caws_Scope_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "CAWS_Mag_Def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "CAWS_Mag_L_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "CAWS_Muzzle_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ToG_VFX_Muzzle",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "M134_Muzzlebooster",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ToG_Flashlight_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ToG_Flashlight_2",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "side_2_empty",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ToG_Flashlight_3",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ToG_Red_Dot_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ToG_Red_Dot_2",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ToG_Red_Dot_3",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ToG_UV_Dot_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ToG_UV_Dot_2",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ToG_UV_Dot_3",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ToG_Comp_Pstl_defmag_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ToG_Comp_Pstl_finemag_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ToG_Comp_Pstl_expmag_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ToG_Comp_Pstl_ergmag_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ToG_Comp_Pstl_Barrel_Long",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ToG_Comp_Pstl_Barrel_Long_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ToG_Comp_AR_Barrel_Long_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ToG_Comp_AR_Barrel_Long_1_SMG",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ToG_Comp_AR_Barrel_Long_2",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ToG_Comp_AR_Barrel_Long_2_SMG",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "WA2000_Mag_Def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "WA2000_Scope_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "WA2000_Mag_L_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "WA2000_Bipod_Unfold_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "WA2000_Bipod_Fold_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "WA2000_NoScope_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "P08_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "P08_Barrel_Long_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "P08_Mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "P08_Mag_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "PKM_Bipod_Fold_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "PKM_Bipod_Unfold_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "TAR21_Mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "TAR21_Mag_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "TAR21_Scope_Rflx_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "TAR21_Muzzle_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "FG42_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "FG42_Barrel_long_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "FG42_Mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "FG42_Mag_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "FG42_Stock_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "FG42_Bipod_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Mosin_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Mosin_Barrel_long_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Mosin_Scope_iron_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Win97_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Placeholder_Muzzle",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G11_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G11_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G11_Mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G11_Mag_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G11_Mag_ext2_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G11_Rail_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ToG_Rail_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ToG_Rail_Block",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ToG_Scope_Block",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ToG_Railmount_placeh",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ToG_Shotgun_Silencer",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G11_Rail_6",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G11_Rail_7",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G11_Rail_8",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G11_Rail_9",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G11_Rail_10",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G11_Rail_11",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G11_Rail_12",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G11_Rail_13",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G11_Rail_14",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G11_Rail_15",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G11_Scope_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G11_Grenadelauncher_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G11_Grip_CAWS_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G11_Bipod_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ToG_Bipod_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G3_Stock_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G3_Muzzle_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G3_Mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G3_Mag_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G3_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G3_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "VSS_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "VSS_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "VSS_Mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "VSS_Mag_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "VSS_Ironsight_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "VSS_Scope_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "VSS_Stock_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Spas12_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Spas12_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Spas12_Stock_fold_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "STG44_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "STG44_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "STG44_Barrel_shrt_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "STG44_Mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "STG44_Stock_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "STG44_Stock_hvy_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "STG44_Stock_erg_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Spas12_Stock_unfold_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G43_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G43_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G43_Mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "G43_Mag_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "GW43_Scope_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "SSG69_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "SSG69_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "SSG69_Mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "SSG69_Mag_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "SSG69_Scope_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "FP6_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "FP6_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "FP6_Ironsight_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "FP6_Stock_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Picatinny_Rail_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Glock17_mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Glock17_Mag_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "SKS_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "SKS_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "SKS_Bay_fld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "SKS_Bay_unfld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "m625_barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "m625_barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "B93R_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "B93R_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "B93R_Under_unfld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "B93R_Under_fld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "ToG_Revolver_freeswap",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Automag_Barrel_50bmg_def",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Automag_Barrel_50bmg_ext",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MicroUZI_freeswap",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "SKS_Scope",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56A_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56B_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56C_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56D_Barrel_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56A_Barrel_shrt_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56B_Barrel_shrt_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56C_Barrel_shrt_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56D_Barrel_shrt_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56A_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56B_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56C_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56D_Barrel_ext_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56A_Mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56B_Mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56C_Mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56D_Mag_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56A_Bay_fld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56B_Bay_fld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56C_Bay_fld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56D_Bay_fld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56A_Bay_unfld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56B_Bay_unfld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56C_Bay_unfld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56D_Bay_unfld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56A_Bolt_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56B_Bolt_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56C_Bolt_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56D_Bolt_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56A_stock_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56A_stock_def_c",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56B_stock_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56B_stock_def_c",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56C_stock_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56C_stock_def_c",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56D_stock_def_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56D_stock_def_c",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56A_stock_erg_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56A_stock_erg_c",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56B_stock_erg_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56B_stock_erg_c",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56C_stock_erg_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56C_stock_erg_c",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56D_stock_erg_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56D_stock_erg_c",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56A_stock_hvy_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56A_stock_hvy_c",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56B_stock_hvy_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56B_stock_hvy_c",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56C_stock_hvy_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56C_stock_hvy_c",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56D_stock_hvy_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Type56D_stock_hvy_c",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Papovka_Bay_unfld_1",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "Papovka2_Bay_unfld_1",
			'ClassDisplayName', "Weapon component",
		}),
	},
	'steam_id', "3101203757",
	'TagBalancing&Difficulty', true,
	'TagWeapons&Items', true,
})