function OnMsg.RevisedMagPropsAddedToFirearms()
    REV_SetupWeapon(B93RR_1, 'B93RR_1_9mm', 'B93RR_1_Magazine', 'MagNormal',
                    {'MagNormal', 'MagLarge'})
    REV_SetupWeapon(USP_1, 'USP_1_9mm', 'USP_1_Magazine', 'MagNormal', {'MagNormal', 'MagLarge'})
    REV_SetupWeapon(VikingMP446_1, 'VikingMP446_1_9mm', 'VikingMP446_1_Magazine', 'MagNormal',
                    {'MagNormal', 'MagLarge'})
    REV_SetupWeapon(PKM_1, 'PKM_1_7_62x54R', 'PKM_1_Magazine', 'MagLarger', {'MagLarger'})
    REV_SetupWeapon(RPD_1, 'RPD_1_762WP', 'RPD_1_Magazine', 'MagLarger', {'MagLarger'})
    REV_SetupWeapon(Gewehr43_1, 'Gewehr43_1_7_92x57', 'Gewehr43_1_Magazine', 'MagNormal',
                    {'MagNormal', 'MagLarge'})
    REV_SetupWeapon(P08_1, 'P08_1_9mm', 'P08_1_Magazine', 'MagNormal', {'MagNormal', 'MagLarge'})
    REV_SetupWeapon(M1911_1, 'M1911_1_45ACP', 'M1911_1_Magazine', 'MagNormal',
                    {'MagNormal', 'MagLarge'})
    REV_SetupWeapon(M76_1, 'M76_1_7_92x57', 'M76_1_Magazine', 'MagNormal', {'MagNormal'})
    REV_SetupWeapon(MAC11_1, 'MAC11_1_380ACP', 'MAC11_1_Magazine', 'MagNormal', {'MagNormal'})
    REV_SetupWeapon(MicroUZI_1, 'MicroUZI_1_9mm', 'MicroUZI_1_Magazine', 'MagNormal',
                    {'MagNormal', 'MagLarge'})
    REV_SetupWeapon(PP91_1, 'PP91_1_9mm', 'PP91_1_Magazine', 'MagNormal', {'MagNormal', 'MagLarge'})
    REV_SetupWeapon(VigM2_1, 'VigM2_1_9mm', 'VigM2_1_Magazine', 'MagNormal', {'MagNormal'})
    REV_SetupWeapon(Delisle_1, 'Delisle_1_45ACP', 'Delisle_1_Magazine', 'MagNormal', {'MagNormal'})
    REV_SetupWeapon(SSG69_1, 'SSG69_1_308Win', 'SSG69_1_Magazine', 'MagNormal',
                    {'MagNormal', 'MagLarge'})
    REV_SetupWeapon(HK23E_1, 'HK23E_1_556', 'HK23E_1_Magazine', 'MagLarger', {'MagLarger'})
    REV_SetupWeapon(HK23ECamo_1, 'HK23E_1_556', 'HK23E_1_Magazine', 'MagLarger', {'MagLarger'})
    REV_SetupWeapon(SteyrScout_1, 'SteyrScout_1_308Win', 'SteyrScout_1_Magazine', 'MagNormal',
                    {'MagNormal'})
    REV_SetupWeapon(StenMK2_1, 'StenMK2_1_9mm', 'StenMK2_1_Magazine', 'MagNormal', {'MagNormal'})
    REV_SetupWeapon(STG44R_1, 'STG44R_1_7_92x33', 'STG44R_1_Magazine', 'MagNormal', {'MagNormal'})
end

function GBOTOG_RevMag_CreateMagazine()
    if not IsMod_loaded('URkxyfE') then
        return
    end

    UndefineClass('B93RR_1_Magazine')
    DefineClass.B93RR_1_Magazine = {
        __parents = {"PistolMag"},
        __generated_by_class = "ModItemInventoryItemCompositeDef",

        Type = "Pistol",
        MagReloadCosts = 10000,
        Id = "B93RR_1_Magazine",
        PistolMag_amount = 1,
        object_class = "PistolMag",
        Modification = "MagNormal",
        Group = "Default",
        Weight = 100,
        Description = T(190884228897, '93R Magazine for 9mm rounds'),
        DisplayNamePlural = T(886895171356, '93R Magazines'),
        PocketM_amount = 1,
        CanBeConsumed = false,
        PistolHolster_amount = 0,
        MagUnloadCosts = 5000,
        Icon = "Mod/KKh3Yhf/Images/B93RR_mag_def.png",
        CategoryPair = "PistolMags",
        PocketL_amount = 0,
        MagazineSize = 20,
        PocketML_amount = 1,
        ScrapParts = 2,
        Carabiner_amount = 0,
        KnifeSheath_amount = 0,
        RifleMag_amount = 1,
        CanAppearInShop = true,
        RestockWeight = 90,
        Repairable = false,
        ExtraAPCosts = 0,
        Platform = "B93RR_1_9mm",
        Caliber = "9mm",
        Tier = 2,
        PocketS_amount = 0,
        AdditionalHint = T(228704926171, '9mm'),
        Cost = 89,
        DisplayName = T(365759529263, '93R Magazine')
    }

    UndefineClass('B93RR_1_MagazineLarge')
    DefineClass.B93RR_1_MagazineLarge = {
        __parents = {"PistolMag"},
        __generated_by_class = "ModItemInventoryItemCompositeDef",

        Type = "Pistol",
        MagReloadCosts = 16000,
        Id = "B93RR_1_MagazineLarge",
        PistolMag_amount = 1,
        object_class = "PistolMag",
        Modification = "MagLarge",
        Group = "Default",
        Weight = 100,
        Description = T(832760315991, '93R Extended Magazine for 9mm rounds'),
        DisplayNamePlural = T(832431141967, '93R Extended Magazines'),
        PocketM_amount = 1,
        CanBeConsumed = false,
        PistolHolster_amount = 0,
        MagUnloadCosts = 8000,
        Icon = "Mod/KKh3Yhf/Images/B93RR_mag_ext.png",
        CategoryPair = "PistolMags",
        PocketL_amount = 0,
        MagazineSize = 30,
        PocketML_amount = 1,
        ScrapParts = 2,
        Carabiner_amount = 0,
        KnifeSheath_amount = 0,
        RifleMag_amount = 1,
        CanAppearInShop = true,
        RestockWeight = 70,
        Repairable = false,
        ExtraAPCosts = 0,
        Platform = "B93RR_1_9mm",
        Caliber = "9mm",
        Tier = 2,
        PocketS_amount = 0,
        AdditionalHint = T(228704926171, '9mm'),
        Cost = 179,
        DisplayName = T(377844436428, '93R Extended Magazine')
    }
    UndefineClass('USP_1_Magazine')
    DefineClass.USP_1_Magazine = {
        __parents = {"PistolMag"},
        __generated_by_class = "ModItemInventoryItemCompositeDef",

        Type = "Pistol",
        MagReloadCosts = 10000,
        Id = "USP_1_Magazine",
        PistolMag_amount = 1,
        object_class = "PistolMag",
        Modification = "MagNormal",
        Group = "Default",
        Weight = 100,
        Description = T(306433861517, 'USP Magazine for 9mm rounds'),
        DisplayNamePlural = T(342413287207, 'USP Magazines'),
        PocketM_amount = 1,
        CanBeConsumed = false,
        PistolHolster_amount = 0,
        MagUnloadCosts = 5000,
        Icon = "Mod/Dau6w/Images/usp_mag_def.png",
        CategoryPair = "PistolMags",
        PocketL_amount = 0,
        MagazineSize = 12,
        PocketML_amount = 1,
        ScrapParts = 2,
        Carabiner_amount = 0,
        KnifeSheath_amount = 0,
        RifleMag_amount = 1,
        CanAppearInShop = true,
        RestockWeight = 90,
        Repairable = false,
        ExtraAPCosts = 0,
        Platform = "USP_1_9mm",
        Caliber = "9mm",
        Tier = 1,
        PocketS_amount = 0,
        AdditionalHint = T(887335898898, '9mm'),
        Cost = 89,
        DisplayName = T(908071330850, 'USP Magazine')
    }
    UndefineClass('USP_1_MagazineLarge')
    DefineClass.USP_1_MagazineLarge = {
        __parents = {"PistolMag"},
        __generated_by_class = "ModItemInventoryItemCompositeDef",

        Type = "Pistol",
        MagReloadCosts = 16000,
        Id = "USP_1_MagazineLarge",
        PistolMag_amount = 1,
        object_class = "PistolMag",
        Modification = "MagLarge",
        Group = "Default",
        Weight = 100,
        Description = T(265371420306, 'USP Extended Magazine for 9mm rounds'),
        DisplayNamePlural = T(136804256170, 'USP Extended Magazines'),
        PocketM_amount = 1,
        CanBeConsumed = false,
        PistolHolster_amount = 0,
        MagUnloadCosts = 8000,
        Icon = "Mod/Dau6w/Images/usp_mag_ex.png",
        CategoryPair = "PistolMags",
        PocketL_amount = 0,
        MagazineSize = 18,
        PocketML_amount = 1,
        ScrapParts = 2,
        Carabiner_amount = 0,
        KnifeSheath_amount = 0,
        RifleMag_amount = 1,
        CanAppearInShop = true,
        RestockWeight = 70,
        Repairable = false,
        ExtraAPCosts = 0,
        Platform = "USP_1_9mm",
        Caliber = "9mm",
        Tier = 1,
        PocketS_amount = 0,
        AdditionalHint = T(887335898898, '9mm'),
        Cost = 179,
        DisplayName = T(860281648327, 'USP Extended Magazine')
    }
    UndefineClass('VikingMP446_1_Magazine')
    DefineClass.VikingMP446_1_Magazine = {
        __parents = {"PistolMag"},
        __generated_by_class = "ModItemInventoryItemCompositeDef",

        Type = "Pistol",
        MagReloadCosts = 10000,
        Id = "VikingMP446_1_Magazine",
        PistolMag_amount = 1,
        object_class = "PistolMag",
        Modification = "MagNormal",
        Group = "Default",
        Weight = 100,
        Description = T(591693920486, 'MP-446 "Viking" Magazine for 9mm rounds'),
        DisplayNamePlural = T(904995660714, 'MP-446 "Viking" Magazines'),
        PocketM_amount = 1,
        CanBeConsumed = false,
        PistolHolster_amount = 0,
        MagUnloadCosts = 5000,
        Icon = "Mod/KKh3Yhf/Images/Viking_Mag_def.png",
        CategoryPair = "PistolMags",
        PocketL_amount = 0,
        MagazineSize = 10,
        PocketML_amount = 1,
        ScrapParts = 2,
        Carabiner_amount = 0,
        KnifeSheath_amount = 0,
        RifleMag_amount = 1,
        CanAppearInShop = true,
        RestockWeight = 90,
        Repairable = false,
        ExtraAPCosts = 0,
        Platform = "VikingMP446_1_9mm",
        Caliber = "9mm",
        Tier = 2,
        PocketS_amount = 0,
        AdditionalHint = T(570324757559, '9mm'),
        Cost = 89,
        DisplayName = T(504324266552, 'MP-446 "Viking" Magazine')
    }
    UndefineClass('VikingMP446_1_MagazineLarge')
    DefineClass.VikingMP446_1_MagazineLarge = {
        __parents = {"PistolMag"},
        __generated_by_class = "ModItemInventoryItemCompositeDef",

        Type = "Pistol",
        MagReloadCosts = 16000,
        Id = "VikingMP446_1_MagazineLarge",
        PistolMag_amount = 1,
        object_class = "PistolMag",
        Modification = "MagLarge",
        Group = "Default",
        Weight = 100,
        Description = T(232000436950, 'MP-446 "Viking" Extended Magazine for 9mm rounds'),
        DisplayNamePlural = T(880661856161, 'MP-446 "Viking" Extended Magazines'),
        PocketM_amount = 1,
        CanBeConsumed = false,
        PistolHolster_amount = 0,
        MagUnloadCosts = 8000,
        Icon = "Mod/KKh3Yhf/Images/Viking_Mag_ext.png",
        CategoryPair = "PistolMags",
        PocketL_amount = 0,
        MagazineSize = 15,
        PocketML_amount = 1,
        ScrapParts = 2,
        Carabiner_amount = 0,
        KnifeSheath_amount = 0,
        RifleMag_amount = 1,
        CanAppearInShop = true,
        RestockWeight = 70,
        Repairable = false,
        ExtraAPCosts = 0,
        Platform = "VikingMP446_1_9mm",
        Caliber = "9mm",
        Tier = 2,
        PocketS_amount = 0,
        AdditionalHint = T(570324757559, '9mm'),
        Cost = 179,
        DisplayName = T(999368972369, 'MP-446 "Viking" Extended Magazine')
    }
    UndefineClass('PKM_1_Magazine')
    DefineClass.PKM_1_Magazine = {
        __parents = {"LargeMag"},
        __generated_by_class = "ModItemInventoryItemCompositeDef",

        Type = "Large",
        MagReloadCosts = 55000,
        Id = "PKM_1_Magazine",
        PistolMag_amount = 0,
        object_class = "LargeMag",
        Modification = "MagLarger",
        Group = "Default",
        Weight = 300,
        Description = T(744924127795, 'PKM Magazine for 7.62x54mmR rounds'),
        DisplayNamePlural = T(976351767611, 'PKM Magazines'),
        PocketM_amount = 0,
        CanBeConsumed = false,
        PistolHolster_amount = 0,
        MagUnloadCosts = 10000,
        Icon = "Mod/Dau6w/Images/pkm_mag_def.png",
        CategoryPair = "MGMags",
        PocketL_amount = 1,
        MagazineSize = 100,
        PocketML_amount = 0,
        ScrapParts = 3,
        Carabiner_amount = 0,
        KnifeSheath_amount = 0,
        RifleMag_amount = 0,
        CanAppearInShop = true,
        RestockWeight = 60,
        Repairable = false,
        ExtraAPCosts = 4000,
        Platform = "PKM_1_7_62x54R",
        Caliber = "7_62x54R",
        Tier = 1,
        PocketS_amount = 0,
        AdditionalHint = T(680517831414, '7.62x54mmR'),
        Cost = 599,
        DisplayName = T(355926253863, 'PKM Magazine')
    }
    UndefineClass('RPD_1_Magazine')
    DefineClass.RPD_1_Magazine = {
        __parents = {"LargeMag"},
        __generated_by_class = "ModItemInventoryItemCompositeDef",

        Type = "Rifle",
        MagReloadCosts = 50000,
        Id = "RPD_1_Magazine",
        PistolMag_amount = 0,
        object_class = "LargeMag",
        Modification = "MagLarger",
        Group = "Default",
        Weight = 300,
        Description = T(437554684829, 'RPD Magazine for 7.62 WP rounds'),
        DisplayNamePlural = T(212170746984, 'RPD Magazines'),
        PocketM_amount = 0,
        CanBeConsumed = false,
        PistolHolster_amount = 0,
        MagUnloadCosts = 5000,
        Icon = "Mod/KKh3Yhf/Images/RPD_mag_def.png",
        CategoryPair = "MGMags",
        PocketL_amount = 1,
        MagazineSize = 100,
        PocketML_amount = 0,
        ScrapParts = 3,
        Carabiner_amount = 0,
        KnifeSheath_amount = 0,
        RifleMag_amount = 0,
        CanAppearInShop = true,
        RestockWeight = 70,
        Repairable = false,
        ExtraAPCosts = 2000,
        Platform = "RPD_1_762WP",
        Caliber = "762WP",
        Tier = 1,
        PocketS_amount = 0,
        AdditionalHint = T(923864900683, '7.62 WP'),
        Cost = 499,
        DisplayName = T(762310836331, 'RPD Magazine')
    }
    UndefineClass('Gewehr43_1_Magazine')
    DefineClass.Gewehr43_1_Magazine = {
        __parents = {"RifleMag"},
        __generated_by_class = "ModItemInventoryItemCompositeDef",

        Type = "Rifle",
        MagReloadCosts = 12000,
        Id = "Gewehr43_1_Magazine",
        PistolMag_amount = 0,
        object_class = "RifleMag",
        Modification = "MagNormal",
        Group = "Default",
        Weight = 200,
        Description = T(305746476611, 'Gewehr 43 Magazine for 7.92×57mm Mauser rounds'),
        DisplayNamePlural = T(503967106811, 'Gewehr 43 Magazines'),
        PocketM_amount = 0,
        CanBeConsumed = false,
        PistolHolster_amount = 0,
        MagUnloadCosts = 6000,
        Icon = "Mod/KKh3Yhf/Images/G43_Mag_def_icon.png",
        CategoryPair = "RifleMags",
        PocketL_amount = 1,
        MagazineSize = 10,
        PocketML_amount = 1,
        ScrapParts = 3,
        Carabiner_amount = 0,
        KnifeSheath_amount = 0,
        RifleMag_amount = 1,
        CanAppearInShop = true,
        RestockWeight = 80,
        Repairable = false,
        ExtraAPCosts = 0,
        Platform = "Gewehr43_1_7_92x57",
        Caliber = "7_92x57",
        Tier = 1,
        PocketS_amount = 0,
        AdditionalHint = T(240927927105, '7.92×57mm Mauser'),
        Cost = 349,
        DisplayName = T(128948796121, 'Gewehr 43 Magazine')
    }
    UndefineClass('Gewehr43_1_MagazineLarge')
    DefineClass.Gewehr43_1_MagazineLarge = {
        __parents = {"RifleMag"},
        __generated_by_class = "ModItemInventoryItemCompositeDef",

        Type = "Rifle",
        MagReloadCosts = 12000,
        Id = "Gewehr43_1_MagazineLarge",
        PistolMag_amount = 0,
        object_class = "RifleMag",
        Modification = "MagLarge",
        Group = "Default",
        Weight = 200,
        Description = T(292123128894, 'Gewehr 43 Extended Magazine for 7.92×57mm Mauser rounds'),
        DisplayNamePlural = T(779010915844, 'Gewehr 43 Extended Magazines'),
        PocketM_amount = 0,
        CanBeConsumed = false,
        PistolHolster_amount = 0,
        MagUnloadCosts = 6000,
        Icon = "Mod/KKh3Yhf/Images/G43_Mag_ext_icon.png",
        CategoryPair = "RifleMags",
        PocketL_amount = 1,
        MagazineSize = 20,
        PocketML_amount = 1,
        ScrapParts = 3,
        Carabiner_amount = 0,
        KnifeSheath_amount = 0,
        RifleMag_amount = 1,
        CanAppearInShop = true,
        RestockWeight = 80,
        Repairable = false,
        ExtraAPCosts = 0,
        Platform = "Gewehr43_1_7_92x57",
        Caliber = "7_92x57",
        Tier = 1,
        PocketS_amount = 0,
        AdditionalHint = T(240927927105, '7.92×57mm Mauser'),
        Cost = 349,
        DisplayName = T(551510318572, 'Gewehr 43 Extended Magazine')
    }
    UndefineClass('P08_1_Magazine')
    DefineClass.P08_1_Magazine = {
        __parents = {"PistolMag"},
        __generated_by_class = "ModItemInventoryItemCompositeDef",

        Type = "Pistol",
        MagReloadCosts = 10000,
        Id = "P08_1_Magazine",
        PistolMag_amount = 1,
        object_class = "PistolMag",
        Modification = "MagNormal",
        Group = "Default",
        Weight = 100,
        Description = T(866790398443, 'Pistole 08 Magazine for 9mm rounds'),
        DisplayNamePlural = T(600921825729, 'Pistole 08 Magazines'),
        PocketM_amount = 1,
        CanBeConsumed = false,
        PistolHolster_amount = 0,
        MagUnloadCosts = 5000,
        Icon = "Mod/KKh3Yhf/Images/P08_Mag_def_icon.png",
        CategoryPair = "PistolMags",
        PocketL_amount = 0,
        MagazineSize = 8,
        PocketML_amount = 1,
        ScrapParts = 2,
        Carabiner_amount = 0,
        KnifeSheath_amount = 0,
        RifleMag_amount = 1,
        CanAppearInShop = true,
        RestockWeight = 90,
        Repairable = false,
        ExtraAPCosts = 0,
        Platform = "P08_1_9mm",
        Caliber = "9mm",
        Tier = 1,
        PocketS_amount = 0,
        AdditionalHint = T(585018992584, '9mm'),
        Cost = 89,
        DisplayName = T(794033305416, 'Pistole 08 Magazine')
    }
    UndefineClass('P08_1_MagazineLarge')
    DefineClass.P08_1_MagazineLarge = {
        __parents = {"PistolMag"},
        __generated_by_class = "ModItemInventoryItemCompositeDef",

        Type = "Pistol",
        MagReloadCosts = 16000,
        Id = "P08_1_MagazineLarge",
        PistolMag_amount = 1,
        object_class = "PistolMag",
        Modification = "MagLarge",
        Group = "Default",
        Weight = 100,
        Description = T(433929430194, 'Pistole 08 Extended Magazine for 9mm rounds'),
        DisplayNamePlural = T(304949831497, 'Pistole 08 Extended Magazines'),
        PocketM_amount = 1,
        CanBeConsumed = false,
        PistolHolster_amount = 0,
        MagUnloadCosts = 8000,
        Icon = "Mod/KKh3Yhf/Images/P08_Mag_ext_icon.png",
        CategoryPair = "PistolMags",
        PocketL_amount = 0,
        MagazineSize = 12,
        PocketML_amount = 1,
        ScrapParts = 2,
        Carabiner_amount = 0,
        KnifeSheath_amount = 0,
        RifleMag_amount = 1,
        CanAppearInShop = true,
        RestockWeight = 70,
        Repairable = false,
        ExtraAPCosts = 0,
        Platform = "P08_1_9mm",
        Caliber = "9mm",
        Tier = 1,
        PocketS_amount = 0,
        AdditionalHint = T(585018992584, '9mm'),
        Cost = 179,
        DisplayName = T(882391682165, 'Pistole 08 Extended Magazine')
    }
    UndefineClass('M1911_1_Magazine')
    DefineClass.M1911_1_Magazine = {
        __parents = {"PistolMag"},
        __generated_by_class = "ModItemInventoryItemCompositeDef",

        Type = "Pistol",
        MagReloadCosts = 8000,
        Id = "M1911_1_Magazine",
        PistolMag_amount = 1,
        object_class = "PistolMag",
        Modification = "MagNormal",
        Group = "Default",
        Weight = 100,
        Description = T(392428909088, '1911 Magazine for 45ACP rounds'),
        DisplayNamePlural = T(458071207803, '1911 Magazines'),
        PocketM_amount = 1,
        CanBeConsumed = false,
        PistolHolster_amount = 0,
        MagUnloadCosts = 4000,
        Icon = "Mod/KKh3Yhf/Images/M1911_Mag_def.png",
        CategoryPair = "PistolMags",
        PocketL_amount = 0,
        MagazineSize = 7,
        PocketML_amount = 1,
        ScrapParts = 2,
        Carabiner_amount = 0,
        KnifeSheath_amount = 0,
        RifleMag_amount = 1,
        CanAppearInShop = true,
        RestockWeight = 90,
        Repairable = false,
        ExtraAPCosts = 0,
        Platform = "M1911_1_45ACP",
        Caliber = "45ACP",
        Tier = 2,
        PocketS_amount = 0,
        AdditionalHint = T(281329946139, '45ACP'),
        Cost = 89,
        DisplayName = T(131475605151, '1911 Magazine')
    }
    UndefineClass('M1911_1_MagazineLarge')
    DefineClass.M1911_1_MagazineLarge = {
        __parents = {"PistolMag"},
        __generated_by_class = "ModItemInventoryItemCompositeDef",

        Type = "Pistol",
        MagReloadCosts = 12000,
        Id = "M1911_1_MagazineLarge",
        PistolMag_amount = 1,
        object_class = "PistolMag",
        Modification = "MagLarge",
        Group = "Default",
        Weight = 100,
        Description = T(299896671261, '1911 Extended Magazine for 45ACP rounds'),
        DisplayNamePlural = T(904528501000, '1911 Extended Magazines'),
        PocketM_amount = 1,
        CanBeConsumed = false,
        PistolHolster_amount = 0,
        MagUnloadCosts = 6000,
        Icon = "Mod/Dau6w/Images/M1911_Mag_ext.png",
        CategoryPair = "PistolMags",
        PocketL_amount = 0,
        MagazineSize = 11,
        PocketML_amount = 1,
        ScrapParts = 2,
        Carabiner_amount = 0,
        KnifeSheath_amount = 0,
        RifleMag_amount = 1,
        CanAppearInShop = true,
        RestockWeight = 70,
        Repairable = false,
        ExtraAPCosts = 0,
        Platform = "M1911_1_45ACP",
        Caliber = "45ACP",
        Tier = 2,
        PocketS_amount = 0,
        AdditionalHint = T(281329946139, '45ACP'),
        Cost = 179,
        DisplayName = T(212554864373, '1911 Extended Magazine')
    }
    UndefineClass('M76_1_Magazine')
    DefineClass.M76_1_Magazine = {
        __parents = {"RifleMag"},
        __generated_by_class = "ModItemInventoryItemCompositeDef",

        Type = "Pistol",
        MagReloadCosts = 10000,
        Id = "M76_1_Magazine",
        PistolMag_amount = 1,
        object_class = "RifleMag",
        Modification = "MagNormal",
        Group = "Default",
        Weight = 100,
        Description = T(877694225656, 'M76 Magazine for 7.92×57mm Mauser rounds'),
        DisplayNamePlural = T(481280114831, 'M76 Magazines'),
        PocketM_amount = 1,
        CanBeConsumed = false,
        PistolHolster_amount = 0,
        MagUnloadCosts = 5000,
        Icon = "Mod/KKh3Yhf/Images/M76_mag_def.png",
        CategoryPair = "SMGMags",
        PocketL_amount = 1,
        MagazineSize = 10,
        PocketML_amount = 1,
        ScrapParts = 2,
        Carabiner_amount = 0,
        KnifeSheath_amount = 0,
        RifleMag_amount = 1,
        CanAppearInShop = true,
        RestockWeight = 90,
        Repairable = false,
        ExtraAPCosts = 0,
        Platform = "M76_1_7_92x57",
        Caliber = "7_92x57",
        Tier = 2,
        PocketS_amount = 0,
        AdditionalHint = T(340655362765, '7.92×57mm Mauser'),
        Cost = 199,
        DisplayName = T(604052661621, 'M76 Magazine')
    }
    UndefineClass('MAC11_1_Magazine')
    DefineClass.MAC11_1_Magazine = {
        __parents = {"SmgMag"},
        __generated_by_class = "ModItemInventoryItemCompositeDef",

        Type = "Rifle",
        MagReloadCosts = 18000,
        Id = "MAC11_1_Magazine",
        PistolMag_amount = 0,
        object_class = "SmgMag",
        Modification = "MagNormal",
        Group = "Default",
        Weight = 150,
        Description = T(809387480429, 'M11 Magazine for .380 ACP rounds'),
        DisplayNamePlural = T(962921646487, 'M11 Magazines'),
        PocketM_amount = 0,
        CanBeConsumed = false,
        PistolHolster_amount = 0,
        MagUnloadCosts = 9000,
        Icon = "Mod/KKh3Yhf/Images/Mac11_Mag_def.png",
        CategoryPair = "SMGMags",
        PocketL_amount = 1,
        MagazineSize = 32,
        PocketML_amount = 1,
        ScrapParts = 2,
        Carabiner_amount = 0,
        KnifeSheath_amount = 0,
        RifleMag_amount = 1,
        CanAppearInShop = true,
        RestockWeight = 90,
        Repairable = false,
        ExtraAPCosts = 0,
        Platform = "MAC11_1_380ACP",
        Caliber = "380ACP",
        Tier = 1,
        PocketS_amount = 0,
        AdditionalHint = T(836523765496, '.380 ACP'),
        Cost = 299,
        DisplayName = T(713476605288, 'M11 Magazine')
    }
    UndefineClass('MicroUZI_1_Magazine')
    DefineClass.MicroUZI_1_Magazine = {
        __parents = {"SmgMag"},
        __generated_by_class = "ModItemInventoryItemCompositeDef",

        Type = "Pistol",
        MagReloadCosts = 16000,
        Id = "MicroUZI_1_Magazine",
        PistolMag_amount = 0,
        object_class = "SmgMag",
        Modification = "MagNormal",
        Group = "Default",
        Weight = 150,
        Description = T(773461400476, 'Micro UZI Magazine for 9mm rounds'),
        DisplayNamePlural = T(118072106289, 'Micro UZI Magazines'),
        PocketM_amount = 0,
        CanBeConsumed = false,
        PistolHolster_amount = 0,
        MagUnloadCosts = 8000,
        Icon = "Mod/KKh3Yhf/Images/MicroUZI_Mag_def.png",
        CategoryPair = "SMGMags",
        PocketL_amount = 1,
        MagazineSize = 20,
        PocketML_amount = 1,
        ScrapParts = 2,
        Carabiner_amount = 0,
        KnifeSheath_amount = 0,
        RifleMag_amount = 1,
        CanAppearInShop = true,
        RestockWeight = 90,
        Repairable = false,
        ExtraAPCosts = 0,
        Platform = "MicroUZI_1_9mm",
        Caliber = "9mm",
        Tier = 1,
        PocketS_amount = 0,
        AdditionalHint = T(911889516024, '9mm'),
        Cost = 199,
        DisplayName = T(222195564859, 'Micro UZI Magazine')
    }
    UndefineClass('MicroUZI_1_MagazineLarge')
    DefineClass.MicroUZI_1_MagazineLarge = {
        __parents = {"SmgMag"},
        __generated_by_class = "ModItemInventoryItemCompositeDef",

        Type = "Rifle",
        MagReloadCosts = 22000,
        Id = "MicroUZI_1_MagazineLarge",
        PistolMag_amount = 0,
        object_class = "SmgMag",
        Modification = "MagLarge",
        Group = "Default",
        Weight = 150,
        Description = T(714163972149, 'Micro UZI Extended Magazine for 9mm rounds'),
        DisplayNamePlural = T(667855121752, 'Micro UZI Extended Magazines'),
        PocketM_amount = 0,
        CanBeConsumed = false,
        PistolHolster_amount = 0,
        MagUnloadCosts = 11000,
        Icon = "Mod/Dau6w/Images/MicroUZI_Mag_ext.png",
        CategoryPair = "SMGMags",
        PocketL_amount = 1,
        MagazineSize = 25,
        PocketML_amount = 1,
        ScrapParts = 2,
        Carabiner_amount = 0,
        KnifeSheath_amount = 0,
        RifleMag_amount = 1,
        CanAppearInShop = true,
        RestockWeight = 70,
        Repairable = false,
        ExtraAPCosts = 0,
        Platform = "MicroUZI_1_9mm",
        Caliber = "9mm",
        Tier = 1,
        PocketS_amount = 0,
        AdditionalHint = T(911889516024, '9mm'),
        Cost = 299,
        DisplayName = T(791094145455, 'Micro UZI Extended Magazine')
    }
    UndefineClass('PP91_1_Magazine')
    DefineClass.PP91_1_Magazine = {
        __parents = {"SmgMag"},
        __generated_by_class = "ModItemInventoryItemCompositeDef",

        Type = "Pistol",
        MagReloadCosts = 10000,
        Id = "PP91_1_Magazine",
        PistolMag_amount = 1,
        object_class = "SmgMag",
        Modification = "MagNormal",
        Group = "Default",
        Weight = 100,
        Description = T(681945637478, 'PP-91 Magazine for 9mm rounds'),
        DisplayNamePlural = T(339337840093, 'PP-91 Magazines'),
        PocketM_amount = 1,
        CanBeConsumed = false,
        PistolHolster_amount = 0,
        MagUnloadCosts = 5000,
        Icon = "Mod/KKh3Yhf/Images/PP91_mag_def.png",
        CategoryPair = "SMGMags",
        PocketL_amount = 1,
        MagazineSize = 20,
        PocketML_amount = 1,
        ScrapParts = 2,
        Carabiner_amount = 0,
        KnifeSheath_amount = 0,
        RifleMag_amount = 1,
        CanAppearInShop = true,
        RestockWeight = 90,
        Repairable = false,
        ExtraAPCosts = 0,
        Platform = "PP91_1_9mm",
        Caliber = "9mm",
        Tier = 1,
        PocketS_amount = 0,
        AdditionalHint = T(337249859786, '9mm'),
        Cost = 199,
        DisplayName = T(550384735723, 'PP-91 Magazine')
    }
    UndefineClass('PP91_1_MagazineLarge')
    DefineClass.PP91_1_MagazineLarge = {
        __parents = {"SmgMag"},
        __generated_by_class = "ModItemInventoryItemCompositeDef",

        Type = "Rifle",
        MagReloadCosts = 18000,
        Id = "PP91_1_MagazineLarge",
        PistolMag_amount = 0,
        object_class = "SmgMag",
        Modification = "MagLarge",
        Group = "Default",
        Weight = 150,
        Description = T(528878663818, 'PP-91 Extended Magazine for 9mm rounds'),
        DisplayNamePlural = T(416433113046, 'PP-91 Extended Magazines'),
        PocketM_amount = 0,
        CanBeConsumed = false,
        PistolHolster_amount = 0,
        MagUnloadCosts = 9000,
        Icon = "Mod/KKh3Yhf/Images/PP91_mag_ext.png",
        CategoryPair = "SMGMags",
        PocketL_amount = 1,
        MagazineSize = 30,
        PocketML_amount = 1,
        ScrapParts = 3,
        Carabiner_amount = 0,
        KnifeSheath_amount = 0,
        RifleMag_amount = 1,
        CanAppearInShop = true,
        RestockWeight = 80,
        Repairable = false,
        ExtraAPCosts = 0,
        Platform = "PP91_1_9mm",
        Caliber = "9mm",
        Tier = 1,
        PocketS_amount = 0,
        AdditionalHint = T(337249859786, '9mm'),
        Cost = 299,
        DisplayName = T(514047773324, 'PP-91 Extended Magazine')
    }
    UndefineClass('VigM2_1_Magazine')
    DefineClass.VigM2_1_Magazine = {
        __parents = {"SmgMag"},
        __generated_by_class = "ModItemInventoryItemCompositeDef",

        Type = "Rifle",
        MagReloadCosts = 18000,
        Id = "VigM2_1_Magazine",
        PistolMag_amount = 0,
        object_class = "SmgMag",
        Modification = "MagNormal",
        Group = "Default",
        Weight = 150,
        Description = T(637149895465, 'Vigneron M2 Magazine for 9mm rounds'),
        DisplayNamePlural = T(124856359936, 'Vigneron M2 Magazines'),
        PocketM_amount = 0,
        CanBeConsumed = false,
        PistolHolster_amount = 0,
        MagUnloadCosts = 9000,
        Icon = "Mod/KKh3Yhf/Images/VigM2_mag_def.png",
        CategoryPair = "SMGMags",
        PocketL_amount = 1,
        MagazineSize = 32,
        PocketML_amount = 1,
        ScrapParts = 2,
        Carabiner_amount = 0,
        KnifeSheath_amount = 0,
        RifleMag_amount = 1,
        CanAppearInShop = true,
        RestockWeight = 90,
        Repairable = false,
        ExtraAPCosts = 0,
        Platform = "VigM2_1_9mm",
        Caliber = "9mm",
        Tier = 1,
        PocketS_amount = 0,
        AdditionalHint = T(488943938366, '9mm'),
        Cost = 299,
        DisplayName = T(463482445245, 'Vigneron M2 Magazine')
    }
    UndefineClass('Delisle_1_Magazine')
    DefineClass.Delisle_1_Magazine = {
        __parents = {"RifleMag"},
        __generated_by_class = "ModItemInventoryItemCompositeDef",

        Type = "Pistol",
        MagReloadCosts = 8000,
        Id = "Delisle_1_Magazine",
        PistolMag_amount = 1,
        object_class = "RifleMag",
        Modification = "MagNormal",
        Group = "Default",
        Weight = 100,
        Description = T(878656493667, 'De Lisle Magazine for 45ACP rounds'),
        DisplayNamePlural = T(109063976791, 'De Lisle Magazines'),
        PocketM_amount = 1,
        CanBeConsumed = false,
        PistolHolster_amount = 0,
        MagUnloadCosts = 4000,
        Icon = "Mod/KKh3Yhf/Images/DeLisle_mag_def.png",
        CategoryPair = "PistolMags",
        PocketL_amount = 0,
        MagazineSize = 7,
        PocketML_amount = 1,
        ScrapParts = 2,
        Carabiner_amount = 0,
        KnifeSheath_amount = 0,
        RifleMag_amount = 1,
        CanAppearInShop = true,
        RestockWeight = 90,
        Repairable = false,
        ExtraAPCosts = 0,
        Platform = "Delisle_1_45ACP",
        Caliber = "45ACP",
        Tier = 1,
        PocketS_amount = 0,
        AdditionalHint = T(729653399652, '45ACP'),
        Cost = 89,
        DisplayName = T(444668579800, 'De Lisle Magazine')
    }
    UndefineClass('SSG69_1_Magazine')
    DefineClass.SSG69_1_Magazine = {
        __parents = {"RifleMag"},
        __generated_by_class = "ModItemInventoryItemCompositeDef",

        Type = "Rifle",
        MagReloadCosts = 12000,
        Id = "SSG69_1_Magazine",
        PistolMag_amount = 0,
        object_class = "RifleMag",
        Modification = "MagNormal",
        Group = "Default",
        Weight = 200,
        Description = T(440383309729, 'SSG 69 Magazine for .308Win rounds'),
        DisplayNamePlural = T(603640135101, 'SSG 69 Magazines'),
        PocketM_amount = 0,
        CanBeConsumed = false,
        PistolHolster_amount = 0,
        MagUnloadCosts = 6000,
        Icon = "Mod/KKh3Yhf/Images/SSG69_Mag_def_icon.png",
        CategoryPair = "RifleMags",
        PocketL_amount = 1,
        MagazineSize = 5,
        PocketML_amount = 1,
        ScrapParts = 3,
        Carabiner_amount = 0,
        KnifeSheath_amount = 0,
        RifleMag_amount = 1,
        CanAppearInShop = true,
        RestockWeight = 80,
        Repairable = false,
        ExtraAPCosts = 0,
        Platform = "SSG69_1_308Win",
        Caliber = "308Win",
        Tier = 2,
        PocketS_amount = 0,
        AdditionalHint = T(943585873547, '.308Win'),
        Cost = 349,
        DisplayName = T(642092548681, 'SSG 69 Magazine')
    }
    UndefineClass('SSG69_1_MagazineLarge')
    DefineClass.SSG69_1_MagazineLarge = {
        __parents = {"RifleMag"},
        __generated_by_class = "ModItemInventoryItemCompositeDef",

        Type = "Rifle",
        MagReloadCosts = 12000,
        Id = "SSG69_1_MagazineLarge",
        PistolMag_amount = 0,
        object_class = "RifleMag",
        Modification = "MagLarge",
        Group = "Default",
        Weight = 200,
        Description = T(466311374768, 'SSG 69 Extended Magazine for .308Win rounds'),
        DisplayNamePlural = T(625558168801, 'SSG 69 Extended Magazines'),
        PocketM_amount = 0,
        CanBeConsumed = false,
        PistolHolster_amount = 0,
        MagUnloadCosts = 6000,
        Icon = "Mod/KKh3Yhf/Images/SSG69_Mag_ext_icon.png",
        CategoryPair = "RifleMags",
        PocketL_amount = 1,
        MagazineSize = 10,
        PocketML_amount = 1,
        ScrapParts = 3,
        Carabiner_amount = 0,
        KnifeSheath_amount = 0,
        RifleMag_amount = 1,
        CanAppearInShop = true,
        RestockWeight = 80,
        Repairable = false,
        ExtraAPCosts = 0,
        Platform = "SSG69_1_308Win",
        Caliber = "308Win",
        Tier = 2,
        PocketS_amount = 0,
        AdditionalHint = T(943585873547, '.308Win'),
        Cost = 349,
        DisplayName = T(967672647915, 'SSG 69 Extended Magazine')
    }
    UndefineClass('HK23E_1_Magazine')
    DefineClass.HK23E_1_Magazine = {
        __parents = {"LargeMag"},
        __generated_by_class = "ModItemInventoryItemCompositeDef",

        Type = "Large",
        MagReloadCosts = 55000,
        Id = "HK23E_1_Magazine",
        PistolMag_amount = 0,
        object_class = "LargeMag",
        Modification = "MagLarger",
        Group = "Default",
        Weight = 300,
        Description = T(803344939575, 'HK23E Magazine for 5.56 rounds'),
        DisplayNamePlural = T(887280373834, 'HK23E Magazines'),
        PocketM_amount = 0,
        CanBeConsumed = false,
        PistolHolster_amount = 0,
        MagUnloadCosts = 10000,
        Icon = "Mod/KKh3Yhf/Images/HK23E_mag_def.png",
        CategoryPair = "MGMags",
        PocketL_amount = 1,
        MagazineSize = 100,
        PocketML_amount = 0,
        ScrapParts = 3,
        Carabiner_amount = 0,
        KnifeSheath_amount = 0,
        RifleMag_amount = 0,
        CanAppearInShop = true,
        RestockWeight = 60,
        Repairable = false,
        ExtraAPCosts = 4000,
        Platform = "HK23E_1_556",
        Caliber = "556",
        Tier = 3,
        PocketS_amount = 0,
        AdditionalHint = T(629568294595, '5.56'),
        Cost = 599,
        DisplayName = T(548709172042, 'HK23E Magazine')
    }
    UndefineClass('SteyrScout_1_Magazine')
    DefineClass.SteyrScout_1_Magazine = {
        __parents = {"RifleMag"},
        __generated_by_class = "ModItemInventoryItemCompositeDef",

        Type = "Rifle",
        MagReloadCosts = 12000,
        Id = "SteyrScout_1_Magazine",
        PistolMag_amount = 0,
        object_class = "RifleMag",
        Modification = "MagNormal",
        Group = "Default",
        Weight = 200,
        Description = T(371252754400, 'Scout Tactical Elite Magazine for .308Win rounds'),
        DisplayNamePlural = T(886950325054, 'Scout Tactical Elite Magazines'),
        PocketM_amount = 0,
        CanBeConsumed = false,
        PistolHolster_amount = 0,
        MagUnloadCosts = 6000,
        Icon = "Mod/Dau6w/Images/Scout_mag_def.png",
        CategoryPair = "RifleMags",
        PocketL_amount = 1,
        MagazineSize = 5,
        PocketML_amount = 1,
        ScrapParts = 3,
        Carabiner_amount = 0,
        KnifeSheath_amount = 0,
        RifleMag_amount = 1,
        CanAppearInShop = true,
        RestockWeight = 80,
        Repairable = false,
        ExtraAPCosts = 0,
        Platform = "SteyrScout_1_308Win",
        Caliber = "308Win",
        Tier = 2,
        PocketS_amount = 0,
        AdditionalHint = T(879919307971, '.308Win'),
        Cost = 349,
        DisplayName = T(351367604629, 'Scout Tactical Elite Magazine')
    }
    UndefineClass('StenMK2_1_Magazine')
    DefineClass.StenMK2_1_Magazine = {
        __parents = {"SmgMag"},
        __generated_by_class = "ModItemInventoryItemCompositeDef",

        Type = "Rifle",
        MagReloadCosts = 18000,
        Id = "StenMK2_1_Magazine",
        PistolMag_amount = 0,
        object_class = "SmgMag",
        Modification = "MagNormal",
        Group = "Default",
        Weight = 150,
        Description = T(125900995687, 'Sten MK II Magazine for 9mm rounds'),
        DisplayNamePlural = T(901287616879, 'Sten MK II Magazines'),
        PocketM_amount = 0,
        CanBeConsumed = false,
        PistolHolster_amount = 0,
        MagUnloadCosts = 9000,
        Icon = "Mod/Dau6w/Images/Sten_mag_def.png",
        CategoryPair = "SMGMags",
        PocketL_amount = 1,
        MagazineSize = 32,
        PocketML_amount = 1,
        ScrapParts = 2,
        Carabiner_amount = 0,
        KnifeSheath_amount = 0,
        RifleMag_amount = 1,
        CanAppearInShop = true,
        RestockWeight = 90,
        Repairable = false,
        ExtraAPCosts = 0,
        Platform = "StenMK2_1_9mm",
        Caliber = "9mm",
        Tier = 1,
        PocketS_amount = 0,
        AdditionalHint = T(153311657254, '9mm'),
        Cost = 299,
        DisplayName = T(271633502099, 'Sten MK II Magazine')
    }
    UndefineClass('STG44R_1_Magazine')
    DefineClass.STG44R_1_Magazine = {
        __parents = {"RifleMag"},
        __generated_by_class = "ModItemInventoryItemCompositeDef",

        Type = "Rifle",
        MagReloadCosts = 22000,
        Id = "STG44R_1_Magazine",
        PistolMag_amount = 0,
        object_class = "RifleMag",
        Modification = "MagNormal",
        Group = "Default",
        Weight = 200,
        Description = T(545385963800, 'Sturmgewehr 44 Magazine for 7.92x33mm rounds'),
        DisplayNamePlural = T(204507308328, 'Sturmgewehr 44 Magazines'),
        PocketM_amount = 0,
        CanBeConsumed = false,
        PistolHolster_amount = 0,
        MagUnloadCosts = 11000,
        Icon = "Mod/KKh3Yhf/Images/STG44_mag_def.png",
        CategoryPair = "RifleMags",
        PocketL_amount = 1,
        MagazineSize = 30,
        PocketML_amount = 1,
        ScrapParts = 3,
        Carabiner_amount = 0,
        KnifeSheath_amount = 0,
        RifleMag_amount = 1,
        CanAppearInShop = true,
        RestockWeight = 90,
        Repairable = false,
        ExtraAPCosts = 0,
        Platform = "STG44R_1_7_92x33",
        Caliber = "7_92x33",
        Tier = 1,
        PocketS_amount = 0,
        AdditionalHint = T(144357171658, '7.92x33mm'),
        Cost = 299,
        DisplayName = T(331234252847, 'Sturmgewehr 44 Magazine')
    }

end
local map = {
    ["MagLarger"] = {
        PlaceObj('WeaponComponentVisual', {
            Icon = "Mod/Dau6w/Images/pkm_mag_def.png",
            param_bindings = false,
            ApplyTo = "PKM_1",
            Entity = "placeholder_7",
            Slot = "Magazine"
        }), PlaceObj('WeaponComponentVisual', {
            Icon = "Mod/KKh3Yhf/Images/RPD_mag_def.png",
            param_bindings = false,
            ApplyTo = "RPD_1",
            Entity = "RPD_mag_def",
            Slot = "Magazine"
        }), PlaceObj('WeaponComponentVisual', {
            Icon = "Mod/KKh3Yhf/Images/HK23E_mag_def.png",
            param_bindings = false,
            ApplyTo = "HK23E_1",
            Entity = "hk23e_mag",
            Slot = "Magazine"
        })
    },
    ["MagLarge"] = {
        PlaceObj('WeaponComponentVisual', {
            Icon = "Mod/KKh3Yhf/Images/B93RR_mag_ext.png",
            param_bindings = false,
            ApplyTo = "B93RR_1",
            Entity = "Beretta_93R_mag_ext",
            Slot = "Magazine"
        }), PlaceObj('WeaponComponentVisual', {
            Icon = "Mod/Dau6w/Images/usp_mag_ex.png",
            param_bindings = false,
            ApplyTo = "USP_1",
            Entity = "uspr_mag_ext",
            Slot = "Magazine"
        }), PlaceObj('WeaponComponentVisual', {
            Icon = "Mod/KKh3Yhf/Images/Viking_Mag_ext.png",
            param_bindings = false,
            ApplyTo = "VikingMP446_1",
            Entity = "Viking_mag_ext",
            Slot = "Magazine"
        }), PlaceObj('WeaponComponentVisual', {
            Icon = "Mod/KKh3Yhf/Images/G43_Mag_ext_icon.png",
            param_bindings = false,
            ApplyTo = "Gewehr43_1",
            Entity = "G43_Mag_ext",
            Slot = "Magazine"
        }), PlaceObj('WeaponComponentVisual', {
            Icon = "Mod/KKh3Yhf/Images/P08_Mag_ext_icon.png",
            param_bindings = false,
            ApplyTo = "P08_1",
            Entity = "P08_Magazine_ext",
            Slot = "Magazine"
        }), PlaceObj('WeaponComponentVisual', {
            Icon = "Mod/Dau6w/Images/M1911_Mag_ext.png",
            param_bindings = false,
            ApplyTo = "M1911_1",
            Entity = "M1911_Mag_ext",
            Slot = "Magazine"
        }), PlaceObj('WeaponComponentVisual', {
            Icon = "Mod/Dau6w/Images/MicroUZI_Mag_ext.png",
            param_bindings = false,
            ApplyTo = "MicroUZI_1",
            Entity = "MicroUZI_Mag_ext",
            Slot = "Magazine"
        }), PlaceObj('WeaponComponentVisual', {
            Icon = "Mod/KKh3Yhf/Images/PP91_mag_ext.png",
            param_bindings = false,
            ApplyTo = "PP91_1",
            Entity = "PP91_Mag_ext",
            Slot = "Magazine"
        }), PlaceObj('WeaponComponentVisual', {
            Icon = "Mod/KKh3Yhf/Images/SSG69_Mag_ext_icon.png",
            param_bindings = false,
            ApplyTo = "SSG69_1",
            Entity = "SSG69_Mag_ext",
            Slot = "Magazine"
        })
    },
    ["MagNormal"] = {
        PlaceObj('WeaponComponentVisual', {
            Icon = "Mod/KKh3Yhf/Images/B93RR_mag_def.png",
            param_bindings = false,
            ApplyTo = "B93RR_1",
            Entity = "Beretta_93R_mag_def",
            Slot = "Magazine"
        }), PlaceObj('WeaponComponentVisual', {
            Icon = "Mod/Dau6w/Images/usp_mag_def.png",
            param_bindings = false,
            ApplyTo = "USP_1",
            Entity = "uspr_mag_def",
            Slot = "Magazine"
        }), PlaceObj('WeaponComponentVisual', {
            Icon = "Mod/KKh3Yhf/Images/Viking_Mag_def.png",
            param_bindings = false,
            ApplyTo = "VikingMP446_1",
            Entity = "Viking_mag_def",
            Slot = "Magazine"
        }), PlaceObj('WeaponComponentVisual', {
            Icon = "Mod/KKh3Yhf/Images/G43_Mag_def_icon.png",
            param_bindings = false,
            ApplyTo = "Gewehr43_1",
            Entity = "G43_Mag_def",
            Slot = "Magazine"
        }), PlaceObj('WeaponComponentVisual', {
            Icon = "Mod/KKh3Yhf/Images/P08_Mag_def_icon.png",
            param_bindings = false,
            ApplyTo = "P08_1",
            Entity = "P08_Magazine_def",
            Slot = "Magazine"
        }), PlaceObj('WeaponComponentVisual', {
            Icon = "Mod/KKh3Yhf/Images/M1911_Mag_def.png",
            param_bindings = false,
            ApplyTo = "M1911_1",
            Entity = "M1911_Mag_def",
            Slot = "Magazine"
        }), PlaceObj('WeaponComponentVisual', {
            Icon = "Mod/KKh3Yhf/Images/M76_mag_def.png",
            param_bindings = false,
            ApplyTo = "M76_1",
            Entity = "m76_mag_def",
            Slot = "Magazine"
        }), PlaceObj('WeaponComponentVisual', {
            Icon = "Mod/KKh3Yhf/Images/Mac11_Mag_def.png",
            param_bindings = false,
            ApplyTo = "MAC11_1",
            Entity = "Mac11_Mag_def",
            Slot = "Magazine"
        }), PlaceObj('WeaponComponentVisual', {
            Icon = "Mod/KKh3Yhf/Images/MicroUZI_Mag_def.png",
            param_bindings = false,
            ApplyTo = "MicroUZI_1",
            Entity = "MicroUZI_Mag_def",
            Slot = "Magazine"
        }), PlaceObj('WeaponComponentVisual', {
            Icon = "Mod/KKh3Yhf/Images/PP91_mag_def.png",
            param_bindings = false,
            ApplyTo = "PP91_1",
            Entity = "PP91_Mag_def",
            Slot = "Magazine"
        }), PlaceObj('WeaponComponentVisual', {
            Icon = "Mod/KKh3Yhf/Images/VigM2_mag_def.png",
            param_bindings = false,
            ApplyTo = "VigM2_1",
            Entity = "VigM2_mag_def",
            Slot = "Magazine"
        }), PlaceObj('WeaponComponentVisual', {
            Icon = "Mod/KKh3Yhf/Images/DeLisle_mag_def.png",
            param_bindings = false,
            ApplyTo = "Delisle_1",
            Entity = "DeLisle_mag_def",
            Slot = "Magazine"
        }), PlaceObj('WeaponComponentVisual', {
            Icon = "Mod/KKh3Yhf/Images/SSG69_Mag_def_icon.png",
            param_bindings = false,
            ApplyTo = "SSG69_1",
            Entity = "SSG69_Mag_def",
            Slot = "Magazine"
        }), PlaceObj('WeaponComponentVisual', {
            Icon = "Mod/Dau6w/Images/Scout_mag_def.png",
            param_bindings = false,
            ApplyTo = "SteyrScout_1",
            Entity = "placeholder_7",
            Slot = "Magazine"
        }), PlaceObj('WeaponComponentVisual', {
            Icon = "Mod/Dau6w/Images/Sten_mag_def.png",
            param_bindings = false,
            ApplyTo = "StenMK2_1",
            Entity = "Sten_mag_def",
            Slot = "Magazine"
        }), PlaceObj('WeaponComponentVisual', {
            Icon = "Mod/KKh3Yhf/Images/STG44_mag_def.png",
            param_bindings = false,
            ApplyTo = "STG44R_1",
            Entity = "STG44R1_mag_def",
            Slot = "Magazine"
        })
    }
}
function GBOTOG_RevMag_WeaponComponentVisualPatch()
    RatTOG_RevMag_ApplyMap(map)
end

function GBOTOG_RevMag_AddClassesToInventoryItemDefs()
    if not IsMod_loaded('URkxyfE') then
        return
    end
    local classes = {
        'B93RR_1_Magazine', 'USP_1_Magazine', 'VikingMP446_1_Magazine', 'PKM_1_Magazine',
        'RPD_1_Magazine', 'Gewehr43_1_Magazine', 'P08_1_Magazine', 'M1911_1_Magazine',
        'M76_1_Magazine', 'MAC11_1_Magazine', 'MicroUZI_1_Magazine', 'PP91_1_Magazine',
        'VigM2_1_Magazine', 'Delisle_1_Magazine', 'SSG69_1_Magazine', 'HK23E_1_Magazine',
        'SteyrScout_1_Magazine', 'StenMK2_1_Magazine', 'STG44R_1_Magazine'
    }
    for _, id in ipairs(classes) do
        InventoryItemDefs[id] = g_Classes[id]
    end
end
